### ISSUE TITLE
Problem saving local storage in Chrome browser

### ISSUE THREAD

**Issue by VanniaAlfaro** [javierbrea/cypress-localstorage-commands#159]
**Describe the bug**
Hello, I installed this plugin because it fits exactly with what I wanted to do, but I'm having some problems in Chrome. I have multiple forms on different pages, the responses of which we save into an object in local storage until the final form where the user submits the form, and the object in local storage gets sent to an API. 
I'm testing to see whether this object is correct when I send it to the API, which requires me to persist local storage so that I can access the final object. During the test run it persists as expected, but at some point, local storage is inexplicably cleared, then starts persisting again!
I already have the chromeWebSecurity set to false.
This seems to work with electron in headless mode.

**Expected behavior**
To work correctly in Chrome browser 

edit:
**Versions**
Cypress 4.12.1
cypress-localstorage-commands 1.2.2
Chrome 86

I added a log so I can see in the cypress UI when they get execute
```
Cypress.Commands.add('clearLS', () => {
  cy.log('Clear Local Storage');
  cy.clearLocalStorageSnapshot();
});

Cypress.Commands.add('restoreLS', () => {
  cy.log('Restore Local Storage');
  cy.restoreLocalStorage();
});

Cypress.Commands.add('SaveLS', () => {
  cy.log('Save Local Storage');
  cy.saveLocalStorage()
});
```
I added the commands on my base test so i can use it n more than one script without calling it all the time
```
BaseTest.PreservingLocalStorage = function(testSuite) {
  describe('Preserving Local Storage', function() {
    before(function() {
      cy.clearLS();
    });

    beforeEach(function() {
      cy.restoreLS()
    });

    afterEach(function() {
      cy.SaveLS();
    });
    
    testSuite();
  });
}
```

This is an example on how the test look it has more "it" than this example
```
BaseTest.PreservingLocalStorage(function() {
  describe('Test of pages', function() {
    it('Select option 1', function() {
      SelectoptionFirstPage
        .VisitTheLanding(url)
        .ClickOnOption(1);
    });

    it('Select Option 2', function() {
        SelectOptionSecondPage
          .ClickOnOption(2);
    });

    it('Select Option 2', function() {
        SelectOptionThirdPage
          .ClickOnOption(3);
    });
  });
});
```

**Comment by javierbrea** [comment]
Hello, thanks for your feedback.
Some additional info about your dependencies versions can be useful, specially your Cypress, cypress-localstorage-commands and Chrome versions.
Also, as the bug is referred to a complex scenario, which I'll probably need to reproduce, please provide a link to your repository, if it is public, or any example producing the error if not.

**Comment by javierbrea** [comment]
Hi @VanniaAlfaro , I didn't notice that you added the extra information I asked for because I didn't get notified, as you edited the issue instead of adding a new comment, sorry for that. I'll try to investigate further as soon as possible 😃

**Comment by javierbrea** [comment]
Hi @VanniaAlfaro , first of all, sorry for the big delay in my response.

I wasn't able to reproduce the problem. Are you still facing the issue?

**Comment by javierbrea** [comment]
Closed by inactivity. Please let me know if the issue is reproducible somehow, and I'll open it again.
