### ISSUE TITLE
Node 10.x support?

### ISSUE THREAD

**Issue by jamesl1001** [javierbrea/cypress-localstorage-commands#210]
**Is your feature request related to a problem? Please describe.**
I am facing the following error when deploying with AWS CodePipeline:
`error cypress-localstorage-commands@1.2.4: The engine "node" is incompatible with this module. Expected version "12.x || 13.x || 14.x || 15.x". Got "10.1.0"`

**Describe the solution you'd like**
Is this package compatible with node 10.x at all?

**Describe alternatives you've considered**
Obviously upgrading node, but I'm just curious if 10.x could be supported?

**Comment by javierbrea** [comment]
Hi @jamesl1001 , I only keep in the package.json `engine` property those versions which are currently tested in the build pipeline (currently all Node.js active versions), but I suppose the package is still compatible with Node 10.x. Could you set the [npm `engine-strict` option](https://docs.npmjs.com/cli/v6/using-npm/config#engine-strict) to false (which is the default npm behavior) until you upgrade your Node version to avoid the error?

**Comment by javierbrea** [comment]
I have finally decided to add Node.js v10.x to the supported engines after testing it, at least while [it is still "active"](https://nodejs.org/en/about/releases/).

Thank you for your feedback @jamesl1001 , I hope to publish a new release modifying the `engines` property as soon as possible. 🙂
