### ISSUE TITLE
Working with Cypress CLI

### ISSUE THREAD

**Issue by musanas** [javierbrea/cypress-localstorage-commands#322]
Hello @javierbrea 

Thank you for this really useful plugin.
Just would like to know, does this work when running tests in cypress CLI mode ? I observed its failing to preserve the local storage when test runs in cli headless mode

Thanks & Warm Regards,

**Comment by javierbrea** [comment]
Hi @musanas

Yes, it works also in headless mode. Could you please provide more information about your Cypress version, configuration, examples of the code, etc? Maybe I can help you to know why it is not working in your case.

**Comment by musanas** [comment]
Hi @javierbrea 

Here are the details

`Cypress package version: 7.5.0
Cypress binary version: 7.5.0
Electron version: 12.0.0-beta.14
Bundled Node version:
14.15.1`

I don't have much of configuration in my default cypress.json, all I have is below, which I think is not causing any issue here
`{
    "watchForFileChanges":false,
    "defaultCommandTimeout":8000
}
`

Example code :
In First test - I am just login to a react app and it saves a localStorage in browser
In Second test - access a child page of the app say ./add-company where I am expecting the app to get the local storage info created by first test
It works normal in cypress gui mode, but fails in cli, where it not able to load the page in second test as the session is not there

Thanks & Warm Regards,

**Comment by javierbrea** [comment]
Thanks @musanas,

There is no any known issue for the versions you are using. In fact, the [E2E tests of the package itself](https://github.com/javierbrea/cypress-localstorage-commands/actions/runs/958677061) are being executed with Cypress 7.4.0, and node versions 12, 14, 15 and 16, and using headless mode.

Could you please provide an example of your code?

**Comment by musanas** [comment]
Hi @javierbrea Apologies for the delayed response

I think I was wrong earlier , just leaned that in cli mode **cypress run** command will isolate specs from each other, and it would result in opening individual browser window for each spec (guess we don't have an option to override this behavior of cypress run). That could have been the reason for the issue that I experienced. As it ran in headless, I didn't get this clue earlier. apologies
I guess we can close this ticket :)

Thanks & Warm Regards,

**Comment by javierbrea** [comment]
Ok @musanas, I close the issue, thank you :)
