### ISSUE TITLE
cypress-localstorage import

### ISSUE THREAD

**Issue by jspaeter** [javierbrea/cypress-localstorage-commands#329]
Hello, just a quick note as i'm new to Cypress and this plugin. If you add Cypress to an Angular 2+ project it comes automatically with typescript. Cypress don't recognise your plugin if the `import "cypress-localstorage-commands"` is in `cypress/support/command.ts`, you're stuck with errors like `cy.clearLocalStorageSnapshot is not a function.`. Instead of having the import in `cypress/support/command.ts`, it should be in `cypress/support/index.ts`.

File structure :
![image](https://user-images.githubusercontent.com/15154959/124892469-33366700-dfda-11eb-8622-42c96901bb47.png)

`cypress/support/index.ts`.
![image](https://user-images.githubusercontent.com/15154959/124892633-5103cc00-dfda-11eb-97c4-080973d3d397.png)

**Comment by javierbrea** [comment]
Hi @jspaeter,
I will add it to the documentation,
Thank you! 😃

**Comment by javierbrea** [comment]
Hi again @jspaeter,

Just a question, were you importing the `support/commands.ts` file from the `index.ts` one? I have just noticed in your code example that the first import you have in the `index.ts` file is the `cypress-localstorage-commands` one, and that you have commented out the `import './commands' line`.

**Comment by jspaeter** [comment]
When you first add the Cypress package, it comes with the comments you can see in my screenshot. The `support/commands.ts` is empty by default.
You have to uncomment the `import './commands` only if you have created custom commands in the `support/commands.ts` file.
For example, here's what I did in my project :

```
// commands.ts
export const login = (username = 'my-user@domain.com', password = 'mypassword') => {
  cy.get('#loginButton').click();

  cy.get('#email').type(username);
  cy.get('#password').type(password);

  cy.get('#loginButton').click();
};
```

```
// index.ts
import { login } from './commands';

Cypress.Commands.add('login', login);
```

**Comment by javierbrea** [comment]
Well, you have to uncomment `import './commands` whenever you have created custom commands, or if you are importing any other commands library in that file. Where do you import your external commands libraries or plugins is more related to a convention of each project.
Do you still receive the same error if you import this plugin in the `commands.ts` file, even when you have uncommented the `import './commands` statement in the `index.ts` file?

**Comment by jspaeter** [comment]
You're right I don't have any problem anymore. Maybe I forgot to uncomment the import command :zany_face:. Sorry to have bothered you for such a stupid mistake !

**Comment by javierbrea** [comment]
Don't worry, no problem 😃
