### ISSUE TITLE
Cypress 8 compatibility

### ISSUE THREAD

**Issue by WIStudent** [javierbrea/cypress-localstorage-commands#330]
**Describe the bug**
Cannot install cypress 8 and cypress-localstorage-commands together

**To Reproduce**
Try installing cypress 8 and cypress-localstorage-commands

**Expected behavior**
Should work with cypress 8

**Logs**
When trying to update cypress 7 to 8:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: cypress@8.0.0
npm ERR! node_modules/cypress
npm ERR!   dev cypress@"^8.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer cypress@"^2.1.0 || 3.x || 4.x || 5.x || 6.x || 7.x" from cypress-localstorage-commands@1.4.5
npm ERR! node_modules/cypress-localstorage-commands
npm ERR!   dev cypress-localstorage-commands@"^1.4.5" from the root project
```

**Operating system, Node.js an npm versions, or browser version (please complete the following information):**
 - OS: Windows 10
 - Node.js: v16.2.0
 - npm: 7.13.0

**Additional context**
It's probably sufficient to add `8.x` to the allowed versions of the cypress peer dependency.

**Comment by javierbrea** [comment]
Cypress version used in E2E tests should be upgraded also in order to check that it works properly.

Thank you! 😃

**Comment by javierbrea** [comment]
Hi again @WIStudent,

Unfortunately, it seems that Cypress v8 does not support `babel.config.js` files. This plugin uses it to configure babel aliases in the E2E tests to load the plugin itself, so it can't be updated "easily".

Until I implement a workaround to be able to run E2E tests or the Cypress team answer to the [issue I have created](https://github.com/cypress-io/cypress/issues/17411), could you try to run `npm i` with the `--legacy-peer-deps` flag? This would make `npm` not trying to install peerDependencies, and would let you decide what version of Cypress to use (if I'm right, you should only receive a warning when installing)
