### ISSUE TITLE
Pass snapshot name to save/restore

### ISSUE THREAD

**Issue by adi518** [javierbrea/cypress-localstorage-commands#376]
I think it could be useful to pass a `snapshot` argument to the `saveLocalStorage` method. For example, I have a case where I need to preserve my login data from `localStorage` between tests, since Cypress clears it by default. With this proposal, you can do:

```js
function loginCommand() {
  // ...
  cy.saveLocalStorage('login')
}
```

And then in my `support/index.js`:

```js
beforeEach(() => {
  cy.restoreLocalStorage('login')
});
```

**Comment by javierbrea** [comment]
Hi @adi518 ,
Thanks for your suggestion. I have just released [v1.7.0](https://github.com/javierbrea/cypress-localstorage-commands/releases/tag/v1.7.0), which already includes this feature 😃
