### ISSUE TITLE
Support for NodeJS 17

### ISSUE THREAD

**Issue by Yash-Singh1** [javierbrea/cypress-localstorage-commands#377]
The package currently doesn't support NodeJS v17:

https://github.com/javierbrea/cypress-localstorage-commands/blob/master/package.json#L74

**Comment by javierbrea** [comment]
Hi @Yash-Singh1 , thanks for the notice.

Released v1.6.0, which already supports NodeJS 17. https://github.com/javierbrea/cypress-localstorage-commands/releases/tag/v1.6.0
