### ISSUE TITLE
restoreLocalStorage do not works

### ISSUE THREAD

**Issue by mmaryo** [javierbrea/cypress-localstorage-commands#390]
Hello
I'm facing an issue with local storage for login
I would like to stay logged between each `it`

```
/// <reference types="Cypress" />

describe('Open Main Screens', () => {
  before(() => {
    cy.clearLocalStorageSnapshot()
    cy.myLogin('abc', 'def') // login with UI
    cy.saveLocalStorage() // should save the current local storage that contains JWT variable
  })

  beforeEach(() => {
    cy.restoreLocalStorage() // should restore local storage and JWT variable 
  })

  it('open reports page', function () {
// I see in local storage JWT variable is not here 
  })
```

I check the local storage in the opened chrome for tests

After login, I saw AuthToken
And in the `it`, AuthToken is not present despite `cy.restoreLocalStorage()` in `beforeEach`

Is it a bug ? or I do not use well this lib ?

Ubuntu 21.10
Last version of node and npm 
Last version of Cypress  : 9.5.2
Last version of localstorage plugin : 1.7.0

Thank you

**Comment by javierbrea** [comment]
Hi @mmaryo, based on your example, it seems that you are not saving the `localStorage` after each test. You should add an `afterEach` hook executing `cy.saveLocalStorage()`. Note that you are executing it only in the `before` hook, so it is executed only once before all tests, not after every test.
You can check the usage examples in the README.md file.
