### ISSUE TITLE
clearLocalStorage()

### ISSUE THREAD

**Issue by stevenvachon** [javierbrea/cypress-localstorage-commands#93]
**Is your feature request related to a problem? Please describe.**
It's good to reset things before starting, especially when not working with a fresh instance of the product.

**Describe the solution you'd like**
A new function/method.

**Comment by javierbrea** [comment]
Hi, there is already available a command called `clearLocalStorageSnapshot`. The "Snapshot" suffix was added to clearly indicate that the real localStorage is not being cleared, only the internal snapshot used by the package to save and restore it is.
Please refer to the [README.md](https://github.com/javierbrea/cypress-localstorage-commands/blob/4eb1af0288620d27f28740b6669d52e263dc2f94/README.md) file for further info.

**Comment by stevenvachon** [comment]
What if the app updates storage after the snapshot was taken?

**Comment by javierbrea** [comment]
The app localStorage is cleaned between every test automatically by Cypress (that is the reason of this package to exist). If you want to clean the localStorage explicitly [Cypress already provides a command: `cy.clearLocalStorage`](https://docs.cypress.io/es/api/commands/clearlocalstorage.html#Usage)

**Comment by stevenvachon** [comment]
Doh, thanks!
