### ISSUE TITLE
getLocalStorage(key).then(value) TypeScript error

### ISSUE THREAD

**Issue by stevenvachon** [javierbrea/cypress-localstorage-commands#94]
**Describe the bug**
```ts
/// <reference types="cypress-localstorage-commands" />

export const getLocalStorage = (key: string): any =>
  cy.getLocalStorage(key).then(value => {
    if (value === null) {
      return value;
    } else {
      return JSON.parse(value);
    }
  });
```
```
error TS2345: Argument of type 'Element' is not assignable to parameter of type 'string'.
```

**Expected behavior**
`value` should be `string | null`.

**Logs**
If applicable, add logs to help explain your problem.

**Operating system, Node.js an npm versions, or browser version (please complete the following information):**
 - OS: macOS 10.15.4
 - Node.js: 12.16.3
 - npm: 6.14.4

**Comment by javierbrea** [comment]
Hi @stevenvachon, thanks for the bug report! 😃  The fix will be released ASAP.
